[package]
name = "variable_chunk_len_reference_impl"
version = "0.0.0"
edition = "2021"

[lib]
name = "variable_chunk_len_reference_impl"
path = "variable_chunk_len_reference_impl.rs"

[dependencies]
arrayref = "0.3.5"